name: dungcony-local

services:
  db:
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: tmdt
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "123456"
    ports:
      - "5432:5432"
    volumes:
      - local_db_data:/var/lib/postgresql/data
      - ./db-dumps/dump.sql:/docker-entrypoint-initdb.d/00-dump.sql:ro
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d tmdt" ]
      interval: 10s
      timeout: 5s
      retries: 20
    command:
      - postgres
      - -c
      - shared_preload_libraries=pg_cron
      - -c
      - cron.database_name=tmdt

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - local_redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 3s
      retries: 20

  app:
    image: dungcony-api:local
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
      SPRING_PROFILES_ACTIVE: dev

      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/tmdt
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: "123456"

      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      SPRING_DATA_REDIS_PASSWORD: ""

    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - local_app_logs:/app/logs

volumes:
  local_db_data:
    driver: local
  local_redis_data:
    driver: local
  local_app_logs:
    driver: local
